title: Just the Docs Template Marino Aguilera
description: A starter template for a Jeykll site using the Just the Docs theme for Marino
theme: just-the-docs

url: https://marino74.github.io/mas-docs

aux_links:
  Template Repository: https://github.com/mas74/mas-docs